#pragma once

#include <AP_HAL/AP_HAL_Boards.h>
#include <AP_MSP/AP_MSP_config.h>
#include <AP_Scripting/AP_Scripting_config.h>
#include <AP_CANManager/AP_CANManager_config.h>
#include <AP_MSP/AP_MSP_config.h>
#include <GCS_MAVLink/GCS_config.h>

#ifndef AP_YUTONG_ENABLED
#define AP_YUTONG_ENABLED 1
#endif

#ifndef AP_YUTONG_BACKEND_DEFAULT_ENABLED
#define AP_YUTONG_BACKEND_DEFAULT_ENABLED AP_YUTONG_ENABLED
#endif

#ifndef AP_YUTONG_BACKEND_CAN_ENABLED
#define AP_YUTONG_BACKEND_CAN_ENABLED AP_YUTONG_ENABLED && HAL_MAX_CAN_PROTOCOL_DRIVERS
#endif

#ifndef AP_YUTONG_DRONECAN_ENABLED
#define AP_YUTONG_DRONECAN_ENABLED (HAL_ENABLE_DRONECAN_DRIVERS && AP_YUTONG_BACKEND_DEFAULT_ENABLED)
#endif

#ifndef AP_YUTONG_LUA_ENABLED
#define AP_YUTONG_LUA_ENABLED AP_YUTONG_BACKEND_DEFAULT_ENABLED && AP_SCRIPTING_ENABLED
#endif

#ifndef AP_YUTONG_MAVLINK_ENABLED
#define AP_YUTONG_MAVLINK_ENABLED AP_YUTONG_BACKEND_DEFAULT_ENABLED && HAL_GCS_ENABLED
#endif

#ifndef HAL_MSP_YUTONG_ENABLED
#define HAL_MSP_YUTONG_ENABLED AP_YUTONG_BACKEND_DEFAULT_ENABLED && HAL_MSP_ENABLED
#endif

#ifndef AP_YUTONG_SIM_ENABLED
#define AP_YUTONG_SIM_ENABLED (CONFIG_HAL_BOARD == HAL_BOARD_SITL && AP_YUTONG_BACKEND_DEFAULT_ENABLED)
#endif

#ifndef HAL_MSP_YUTONG_ENABLED
#define HAL_MSP_YUTONG_ENABLED (AP_YUTONG_BACKEND_DEFAULT_ENABLED && HAL_MSP_ENABLED)
#endif

#ifndef AP_YUTONG_CUSTOM_CAN_ENABLED
#define AP_YUTONG_CUSTOM_CAN_ENABLED AP_YUTONG_BACKEND_DEFAULT_ENABLED && AP_YUTONG_BACKEND_CAN_ENABLED
#endif

#ifndef AP_YUTONG_WASP_ENABLED
#define AP_YUTONG_WASP_ENABLED AP_YUTONG_BACKEND_DEFAULT_ENABLED
#endif

